### ISSUE TITLE
向SP汇报短信发送结果

### ISSUE THREAD

**Issue by wushijing2011** [flyingfisher/node-cmpp-3#1]
请问，如果向同一个号码连续发送两条短信，在 “deliver” 事件中如何确定回报的是哪一条短息的结果，请问回报的Msg_Content 中的Msg_Id可否由SP生成，感谢

**Comment by flyingfisher** [comment]
deliver 事件中有Msg_Id，可以通过Msg_Id检查。
send成功后，会返回一个Msg_Id。

**Comment by haocenxu** [comment]
发送单条短信时的 Msg_Id 似乎是全 0 ？相关代码完全跳过了对 Msg_Id 的处理。发送长短信的部分倒是做了特别处理。

**Comment by lawrence-peng** [comment]
有cmpp2的版本吗？
